// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2c7QeXYWwtrOk1z_z2S7eUVovX3ut6wM',
    appId: '1:92391211487:web:77d02a7dc71a9ae006046a',
    messagingSenderId: '92391211487',
    projectId: 'smart-learn-de011',
    authDomain: 'smart-learn-de011.firebaseapp.com',
    storageBucket: 'smart-learn-de011.firebasestorage.app',
    measurementId: 'G-7MPZ7KGW1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV50k5cC-OcJgfBKvbJYNuipKoFyB65Z4',
    appId: '1:92391211487:android:5f0244be96dc564206046a',
    messagingSenderId: '92391211487',
    projectId: 'smart-learn-de011',
    storageBucket: 'smart-learn-de011.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD1KsJtX2LkLqMSDMSNOVgLmezelsRz58',
    appId: '1:92391211487:ios:42043e219d07ff1f06046a',
    messagingSenderId: '92391211487',
    projectId: 'smart-learn-de011',
    storageBucket: 'smart-learn-de011.firebasestorage.app',
    iosBundleId: 'com.example.smartLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD1KsJtX2LkLqMSDMSNOVgLmezelsRz58',
    appId: '1:92391211487:ios:42043e219d07ff1f06046a',
    messagingSenderId: '92391211487',
    projectId: 'smart-learn-de011',
    storageBucket: 'smart-learn-de011.firebasestorage.app',
    iosBundleId: 'com.example.smartLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2c7QeXYWwtrOk1z_z2S7eUVovX3ut6wM',
    appId: '1:92391211487:web:05779968bd9f872106046a',
    messagingSenderId: '92391211487',
    projectId: 'smart-learn-de011',
    authDomain: 'smart-learn-de011.firebaseapp.com',
    storageBucket: 'smart-learn-de011.firebasestorage.app',
    measurementId: 'G-NMX9267L3T',
  );
}
